name: Push Image

on:
  release:
    types:
      - published

jobs:
  push_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_URI: ghcr.io/tobyhs/terraform-lock-checker:${{ github.ref_name }}
      LATEST_IMAGE_URI: ghcr.io/tobyhs/terraform-lock-checker:latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t "$IMAGE_URI" .
      - name: Push Image
        run: |
          docker tag "$IMAGE_URI" "$LATEST_IMAGE_URI"
          docker push "$IMAGE_URI"
          docker push "$LATEST_IMAGE_URI"
