name: Push Image

on:
  release:
    types:
      - published

jobs:
  push_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/tobyhs/terraform-lock-checker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image
        run: |
          TAGGED_IMAGE_NAME="${IMAGE_NAME}:$(sed 's/^v//' <<< ${{ github.ref_name }})"
          LATEST_IMAGE_NAME="${IMAGE_NAME}:latest"
          docker build -t "$TAGGED_IMAGE_NAME" .
          docker tag "$TAGGED_IMAGE_NAME" "$LATEST_IMAGE_NAME"
          docker push "$TAGGED_IMAGE_NAME"
          docker push "$LATEST_IMAGE_NAME"
